FROM kathara/pox:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends stress-ng gcc python3.9-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    SETUPTOOLS_USE_DISTUTILS=stdlib python3.9 -m pip install --no-cache-dir --break-system-packages ryu eventlet==0.30.2
    